//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoHorarioSet
    {
        public int IdAlumnoHorario { get; set; }
        public int IdRolAlumno { get; set; }
        public int IdRolCiudadActivaHorario { get; set; }
        public string TipoHorario { get; set; }
    }
}
