//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionRecibo
    {
        public int IdAsignacionRecibo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int NumRecibo { get; set; }
        public int IdPersona { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
