//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiudadActivaLocaciones
    {
        public int IdCiudadActivaLocaciones { get; set; }
        public int IdRolCiudadActiva { get; set; }
        public int IdLocacion { get; set; }
    
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        public virtual Locacion Locacion { get; set; }
    }
}
