//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaCiudad
    {
        public int IdLineaCiudad { get; set; }
        public int IdLinea { get; set; }
        public int IdCiudad { get; set; }
    
        public virtual Linea Linea { get; set; }
        public virtual Ciudad Ciudad { get; set; }
    }
}
