//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaDocentes
    {
        public int IdLineaDocente { get; set; }
        public int IdLinea { get; set; }
        public int IdRolEmpleado { get; set; }
    
        public virtual RolEmpleado RolEmpleado { get; set; }
        public virtual Linea Linea { get; set; }
    }
}
