//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisoAcceso
    {
        public int IdPermisoAcceso { get; set; }
        public int IdPermiso { get; set; }
        public string DetalleAcceso { get; set; }
        public bool PermisoActivo { get; set; }
    
        public virtual Permiso Permiso { get; set; }
    }
}
