//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolAlumno
    {
        public int IdRolAlumno { get; set; }
        public int IdPersona { get; set; }
        public int IdCapacitacion { get; set; }
        public int IdInformeCiudadHorarios { get; set; }
        public int IdEstadoAlumno { get; set; }
    
        public virtual EstadoAlumno EstadoAlumno { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
