//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolVendedor
    {
        public int IdRolVendedor { get; set; }
        public int IdPersona { get; set; }
        public int IdSubgerente { get; set; }
        public int IdGerente { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        public virtual Persona Persona2 { get; set; }
    }
}
