//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCiudadEquiposSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsignacionCiudadEquiposSet()
        {
            this.CiudadEquiposSet = new HashSet<CiudadEquiposSet>();
            this.CiudadProductosSet = new HashSet<CiudadProductosSet>();
            this.EnvioCiudadEquiposSet = new HashSet<EnvioCiudadEquiposSet>();
        }
    
        public long IdAsignacionCiudadEquipo { get; set; }
        public string Fecha { get; set; }
        public long IdRolCiudadActiva { get; set; }
        public long IdEstadoAsignacionEquipo { get; set; }
    
        public virtual RolCiudadActivaSet RolCiudadActivaSet { get; set; }
        public virtual EstadoAsignacionEquipoSet EstadoAsignacionEquipoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiudadEquiposSet> CiudadEquiposSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiudadProductosSet> CiudadProductosSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvioCiudadEquiposSet> EnvioCiudadEquiposSet { get; set; }
    }
}
