//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChequeSet()
        {
            this.GastoChequeSet = new HashSet<GastoChequeSet>();
            this.PagoChequeSet = new HashSet<PagoChequeSet>();
            this.PagoLocalChequeSet = new HashSet<PagoLocalChequeSet>();
        }
    
        public long IdCheque { get; set; }
        public string Banco { get; set; }
        public string Titular { get; set; }
        public string NroCheque { get; set; }
        public string FechaEmision { get; set; }
        public string FechaPago { get; set; }
        public string Monto { get; set; }
        public long IdTipoCheque { get; set; }
        public long IdEstadoCheque { get; set; }
    
        public virtual TipoChequeSet TipoChequeSet { get; set; }
        public virtual EstadoChequeSet EstadoChequeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoChequeSet> GastoChequeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoChequeSet> PagoChequeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalChequeSet> PagoLocalChequeSet { get; set; }
    }
}
