//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiudadFechasHorariosSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CiudadFechasHorariosSet()
        {
            this.RolAlumnoPracticasSet = new HashSet<RolAlumnoPracticasSet>();
        }
    
        public long IdCiudadFechasHorarios { get; set; }
        public long IdRolCiudadActiva { get; set; }
        public string Fecha { get; set; }
        public string IdRolCiudadActivaHorarios { get; set; }
    
        public virtual RolCiudadActivaSet RolCiudadActivaSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolAlumnoPracticasSet> RolAlumnoPracticasSet { get; set; }
    }
}
