//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancoSet
    {
        public long IdCuentaBanco { get; set; }
        public string Banco { get; set; }
        public string NroCuenta { get; set; }
        public string TipoCuenta { get; set; }
        public string CBU { get; set; }
        public string Titular { get; set; }
        public string Cuit { get; set; }
        public string Observaciones { get; set; }
        public bool CuentaActiva { get; set; }
    }
}
