//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositoSet
    {
        public long IdDeposito { get; set; }
        public long IdPersona { get; set; }
        public string Fecha { get; set; }
        public string Monto { get; set; }
        public long IdCuentaBanco { get; set; }
        public long IdEstadoDeposito { get; set; }
    }
}
