//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompraSet
    {
        public long IdDetalleCompra { get; set; }
        public long IdCompra { get; set; }
        public long IdProducto { get; set; }
        public string Cantidad { get; set; }
        public string Precio { get; set; }
    
        public virtual CompraSet CompraSet { get; set; }
        public virtual ProductosSet ProductosSet { get; set; }
    }
}
