//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoInternoEfectivoSet
    {
        public long IdMovimientoInternoEfectivo { get; set; }
        public long IdCajaEfectivoOrigen { get; set; }
        public string FechaMovimientoInternoEfectivo { get; set; }
        public long IdcajaEfectivoDestino { get; set; }
        public string Monto { get; set; }
        public string Observaciones { get; set; }
    
        public virtual CajaEfectivoSet CajaEfectivoSet { get; set; }
        public virtual CajaEfectivoSet CajaEfectivoSet1 { get; set; }
    }
}
