//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoLocalCajaEfectivoSet
    {
        public long IdPagoLocalCajaEfectivo { get; set; }
        public long IdPagoLocal { get; set; }
        public string FechaPagoCajaEfectivo { get; set; }
        public string Monto { get; set; }
        public long IdCajaEfectivo { get; set; }
    }
}
