//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoSet
    {
        public long IdPago { get; set; }
        public long IdPlanVendedorAlumno { get; set; }
        public string MontoPagado { get; set; }
        public long IdFormaPago { get; set; }
        public long IdItemPagado { get; set; }
        public string NroRecibo { get; set; }
    }
}
