//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoLocalTarjetaSet
    {
        public long IdPagoLocalTarjeta { get; set; }
        public long IdPagoLocal { get; set; }
        public long IdTarjetaPropia { get; set; }
        public string CantCuotas { get; set; }
        public string Monto { get; set; }
    
        public virtual PagoLocalSet PagoLocalSet { get; set; }
        public virtual TarjetaPropiaSet TarjetaPropiaSet { get; set; }
    }
}
