//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanVendedorAlumnoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanVendedorAlumnoSet()
        {
            this.PagoSet = new HashSet<PagoSet>();
        }
    
        public long IdPlanVendedorAlumno { get; set; }
        public string NroRecibo { get; set; }
        public long IdRolCiudadActivaPlan { get; set; }
        public long IdRolAlumno { get; set; }
        public long IdRolVendedor { get; set; }
        public string ObservacionGerente { get; set; }
        public string ObservacionOficinaBaires { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoSet> PagoSet { get; set; }
        public virtual RolVendedor RolVendedor { get; set; }
        public virtual RolCiudadActivaPlanSet RolCiudadActivaPlanSet { get; set; }
        public virtual RolAlumno RolAlumno { get; set; }
    }
}
