//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendicionDepositoSet
    {
        public long IdRendicionDeposito { get; set; }
        public long IdRendicionEmpleadoCiudad { get; set; }
        public long IdDeposito { get; set; }
    
        public virtual DepositoSet DepositoSet { get; set; }
        public virtual RendicionPersonaCiudadSet RendicionPersonaCiudadSet { get; set; }
    }
}
