//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendicionVentaEquipoSet
    {
        public long IdRendicionVentaEquipo { get; set; }
        public long IdPago { get; set; }
        public long IdArmadoEquipo { get; set; }
        public long IdEstadoVenta { get; set; }
    
        public virtual ArmadoEquipoSet ArmadoEquipoSet { get; set; }
        public virtual EstadoVentaSet EstadoVentaSet { get; set; }
        public virtual PagoSet PagoSet { get; set; }
    }
}
