//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolAlumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolAlumno()
        {
            this.AlumnoHorarioSet = new HashSet<AlumnoHorarioSet>();
            this.PlanVendedorAlumnoSet = new HashSet<PlanVendedorAlumnoSet>();
            this.RolAlumnoPracticasSet = new HashSet<RolAlumnoPracticasSet>();
            this.RolAlumnoPresentismoSet = new HashSet<RolAlumnoPresentismoSet>();
        }
    
        public long IdRolAlumno { get; set; }
        public long IdPersona { get; set; }
        public long IdCapacitacion { get; set; }
        public long IdEstadoAlumno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoHorarioSet> AlumnoHorarioSet { get; set; }
        public virtual CapacitacionSet CapacitacionSet { get; set; }
        public virtual EstadoAlumno EstadoAlumno { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanVendedorAlumnoSet> PlanVendedorAlumnoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolAlumnoPracticasSet> RolAlumnoPracticasSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolAlumnoPresentismoSet> RolAlumnoPresentismoSet { get; set; }
    }
}
