//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolCiudadActivaPlanSet
    {
        public long IdRolCiudadActivaPlan { get; set; }
        public long IdRolCiudadActiva { get; set; }
        public long IdPlanBase { get; set; }
        public string ValorMatricula { get; set; }
        public string CantCuotas { get; set; }
        public string ValorCuota { get; set; }
        public string ValorDescuento { get; set; }
        public string ValorCertificado { get; set; }
        public string ComisionIda { get; set; }
        public string ComisionVuelta { get; set; }
        public string ComisionCertificado { get; set; }
    }
}
