//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolLocacionSalonSet
    {
        public long IdRolLocacionSalon { get; set; }
        public long IdLocacion { get; set; }
        public string Tamaño { get; set; }
        public string Mesas { get; set; }
        public string Sillas { get; set; }
        public string AireAcondicionado { get; set; }
        public string Calefaccion { get; set; }
    
        public virtual LocacionSet LocacionSet { get; set; }
    }
}
