//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolLocacionAlojamientoSet
    {
        public long IdRolLocacionAlojamiento { get; set; }
        public long IdLocacion { get; set; }
        public string Dias { get; set; }
        public string CantDormitorios { get; set; }
        public string CantCamas { get; set; }
    
        public virtual LocacionSet LocacionSet { get; set; }
    }
}
