//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class SueldoPagoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SueldoPagoSet()
        {
            this.PagoLocalSueldoSet = new HashSet<PagoLocalSueldoSet>();
            this.RendicionSueldoSet = new HashSet<RendicionSueldoSet>();
        }
    
        public long IdSueldoPago { get; set; }
        public long IdRolEmpleado { get; set; }
        public string Periodo { get; set; }
        public string Monto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalSueldoSet> PagoLocalSueldoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionSueldoSet> RendicionSueldoSet { get; set; }
        public virtual RolEmpleado RolEmpleado { get; set; }
    }
}
