//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaPropiaSet
    {
        public long IdTarjetaPropia { get; set; }
        public string Emsior { get; set; }
        public string NroTarjeta { get; set; }
        public string FechaVto { get; set; }
        public string CodSeguridad { get; set; }
        public string Titular { get; set; }
        public string DNI { get; set; }
    }
}
