//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Client.Entities_Client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SqliteClientDataBaseEntities1 : DbContext
    {
        public SqliteClientDataBaseEntities1()
            : base("name=SqliteClientDataBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlumnoHorarioSet> AlumnoHorarioSet { get; set; }
        public virtual DbSet<ArmadoEquipoSet> ArmadoEquipoSet { get; set; }
        public virtual DbSet<AsignacionCiudadEquiposSet> AsignacionCiudadEquiposSet { get; set; }
        public virtual DbSet<AsignacionReciboSet> AsignacionReciboSet { get; set; }
        public virtual DbSet<CajaEfectivoSet> CajaEfectivoSet { get; set; }
        public virtual DbSet<CapacitacionSet> CapacitacionSet { get; set; }
        public virtual DbSet<ChequePropioSet> ChequePropioSet { get; set; }
        public virtual DbSet<ChequeSet> ChequeSet { get; set; }
        public virtual DbSet<CiudadActivaLocacionesSet> CiudadActivaLocacionesSet { get; set; }
        public virtual DbSet<CiudadEquiposSet> CiudadEquiposSet { get; set; }
        public virtual DbSet<CiudadFechasHorariosSet> CiudadFechasHorariosSet { get; set; }
        public virtual DbSet<CiudadPersonalSet> CiudadPersonalSet { get; set; }
        public virtual DbSet<CiudadProductosSet> CiudadProductosSet { get; set; }
        public virtual DbSet<CiudadSet> CiudadSet { get; set; }
        public virtual DbSet<CoeficTarjetasSet> CoeficTarjetasSet { get; set; }
        public virtual DbSet<CompraSet> CompraSet { get; set; }
        public virtual DbSet<CondicionEmpleadoSet> CondicionEmpleadoSet { get; set; }
        public virtual DbSet<CuentaBancoSet> CuentaBancoSet { get; set; }
        public virtual DbSet<CuentaBancoTerceroSet> CuentaBancoTerceroSet { get; set; }
        public virtual DbSet<DepositoSet> DepositoSet { get; set; }
        public virtual DbSet<DetalleArmadoEquipoSet> DetalleArmadoEquipoSet { get; set; }
        public virtual DbSet<DetalleCompraSet> DetalleCompraSet { get; set; }
        public virtual DbSet<DetalleCondicionEmpleado> DetalleCondicionEmpleado { get; set; }
        public virtual DbSet<DiaSet> DiaSet { get; set; }
        public virtual DbSet<EnvioCiudadEquiposSet> EnvioCiudadEquiposSet { get; set; }
        public virtual DbSet<EnvioSet> EnvioSet { get; set; }
        public virtual DbSet<EstadoAlumno> EstadoAlumno { get; set; }
        public virtual DbSet<EstadoAsignacionEquipoSet> EstadoAsignacionEquipoSet { get; set; }
        public virtual DbSet<EstadoChequeSet> EstadoChequeSet { get; set; }
        public virtual DbSet<EstadoCompraSet> EstadoCompraSet { get; set; }
        public virtual DbSet<EstadoDepositoSet> EstadoDepositoSet { get; set; }
        public virtual DbSet<EstadoPagoTarjetaSet> EstadoPagoTarjetaSet { get; set; }
        public virtual DbSet<EstadoRendicionSet> EstadoRendicionSet { get; set; }
        public virtual DbSet<EstadoTransferenciaSet> EstadoTransferenciaSet { get; set; }
        public virtual DbSet<EstadoVentaSet> EstadoVentaSet { get; set; }
        public virtual DbSet<FormaPagoLocalSet> FormaPagoLocalSet { get; set; }
        public virtual DbSet<FormaPagoSet> FormaPagoSet { get; set; }
        public virtual DbSet<GastoBaseSet> GastoBaseSet { get; set; }
        public virtual DbSet<GastoChequeSet> GastoChequeSet { get; set; }
        public virtual DbSet<GastoLocalSet> GastoLocalSet { get; set; }
        public virtual DbSet<HorarioSet> HorarioSet { get; set; }
        public virtual DbSet<ItemPagadoSet> ItemPagadoSet { get; set; }
        public virtual DbSet<LocacionRolLocadorSet> LocacionRolLocadorSet { get; set; }
        public virtual DbSet<LocacionSet> LocacionSet { get; set; }
        public virtual DbSet<LocalidadSet> LocalidadSet { get; set; }
        public virtual DbSet<MovimientoInternoEfectivoSet> MovimientoInternoEfectivoSet { get; set; }
        public virtual DbSet<PagoChequeSet> PagoChequeSet { get; set; }
        public virtual DbSet<PagoLocalCajaEfectivoSet> PagoLocalCajaEfectivoSet { get; set; }
        public virtual DbSet<PagoLocalChequePropioSet> PagoLocalChequePropioSet { get; set; }
        public virtual DbSet<PagoLocalChequeSet> PagoLocalChequeSet { get; set; }
        public virtual DbSet<PagoLocalEnvioSet> PagoLocalEnvioSet { get; set; }
        public virtual DbSet<PagoLocalSet> PagoLocalSet { get; set; }
        public virtual DbSet<PagoLocalSueldoSet> PagoLocalSueldoSet { get; set; }
        public virtual DbSet<PagoLocalTarjetaSet> PagoLocalTarjetaSet { get; set; }
        public virtual DbSet<PagoLocalTransferenciaSet> PagoLocalTransferenciaSet { get; set; }
        public virtual DbSet<PagoSet> PagoSet { get; set; }
        public virtual DbSet<PagoTarjetaSet> PagoTarjetaSet { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<PermisoAcceso> PermisoAcceso { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<PlanBaseSet> PlanBaseSet { get; set; }
        public virtual DbSet<PlanVendedorAlumnoSet> PlanVendedorAlumnoSet { get; set; }
        public virtual DbSet<ProductosSet> ProductosSet { get; set; }
        public virtual DbSet<ProveedorSet> ProveedorSet { get; set; }
        public virtual DbSet<PuestoSet> PuestoSet { get; set; }
        public virtual DbSet<ReciboSet> ReciboSet { get; set; }
        public virtual DbSet<RendicionDepositoSet> RendicionDepositoSet { get; set; }
        public virtual DbSet<RendicionGastoSet> RendicionGastoSet { get; set; }
        public virtual DbSet<RendicionPagoSet> RendicionPagoSet { get; set; }
        public virtual DbSet<RendicionPersonaCiudadSet> RendicionPersonaCiudadSet { get; set; }
        public virtual DbSet<RendicionSueldoSet> RendicionSueldoSet { get; set; }
        public virtual DbSet<RendicionValeSet> RendicionValeSet { get; set; }
        public virtual DbSet<RendicionVentaEquipoSet> RendicionVentaEquipoSet { get; set; }
        public virtual DbSet<RolAlumno> RolAlumno { get; set; }
        public virtual DbSet<RolAlumnoPracticasSet> RolAlumnoPracticasSet { get; set; }
        public virtual DbSet<RolAlumnoPresentismoSet> RolAlumnoPresentismoSet { get; set; }
        public virtual DbSet<RolCiudadActivaGastosSet> RolCiudadActivaGastosSet { get; set; }
        public virtual DbSet<RolCiudadActivaHorarioSet> RolCiudadActivaHorarioSet { get; set; }
        public virtual DbSet<RolCiudadActivaPlanSet> RolCiudadActivaPlanSet { get; set; }
        public virtual DbSet<RolCiudadActivaSet> RolCiudadActivaSet { get; set; }
        public virtual DbSet<RolCiudadEnProcesoSet> RolCiudadEnProcesoSet { get; set; }
        public virtual DbSet<RolDocenteSet> RolDocenteSet { get; set; }
        public virtual DbSet<RolEmpleado> RolEmpleado { get; set; }
        public virtual DbSet<RolLocacionAlojamientoSet> RolLocacionAlojamientoSet { get; set; }
        public virtual DbSet<RolLocacionSalonSet> RolLocacionSalonSet { get; set; }
        public virtual DbSet<RolLocadorSet> RolLocadorSet { get; set; }
        public virtual DbSet<RolVendedor> RolVendedor { get; set; }
        public virtual DbSet<SueldoPagoSet> SueldoPagoSet { get; set; }
        public virtual DbSet<TarjetaPropiaSet> TarjetaPropiaSet { get; set; }
        public virtual DbSet<TipoChequeSet> TipoChequeSet { get; set; }
        public virtual DbSet<TransferenciaSet> TransferenciaSet { get; set; }
        public virtual DbSet<ValeFinanciacionSet> ValeFinanciacionSet { get; set; }
        public virtual DbSet<ValeSet> ValeSet { get; set; }
    }
}
