//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoHorario
    {
        public int IdAlumnoHorario { get; set; }
        public int IdRolAlumno { get; set; }
        public int IdRolCiudadActivaHorario { get; set; }
        public string TipoHorario { get; set; }
    
        public virtual RolCiudadActivaHorario RolCiudadActivaHorario { get; set; }
        public virtual RolAlumno RolAlumno { get; set; }
    }
}
