//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCiudadEquipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsignacionCiudadEquipos()
        {
            this.CiudadEquipos = new HashSet<CiudadEquipos>();
            this.CiudadProductos = new HashSet<CiudadProductos>();
            this.EnvioCiudadEquipos = new HashSet<EnvioCiudadEquipos>();
        }
    
        public int IdAsignacionCiudadEquipo { get; set; }
        public string Fecha { get; set; }
        public int IdRolCiudadActiva { get; set; }
        public int IdEstadoAsignacionEquipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiudadEquipos> CiudadEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiudadProductos> CiudadProductos { get; set; }
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        public virtual EstadoAsignacionEquipo EstadoAsignacionEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvioCiudadEquipos> EnvioCiudadEquipos { get; set; }
    }
}
