//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCiudadEquipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsignacionCiudadEquipos()
        {
            this.CiudadEquipos = new HashSet<CiudadEquipos>();
            this.CiudadProductos = new HashSet<CiudadProductos>();
        }
    
        public int IdAsignacionCiudadEquipo { get; set; }
        public string Fecha { get; set; }
        public int IdRolCiudadActiva { get; set; }
        public int IdEstadoAsignacionEquipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiudadEquipos> CiudadEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiudadProductos> CiudadProductos { get; set; }
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        public virtual EstadoAsignacionEquipo EstadoAsignacionEquipo { get; set; }
    }
}
