//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaEfectivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajaEfectivo()
        {
            this.MovimientoInternoEfectivo = new HashSet<MovimientoInternoEfectivo>();
            this.MovimientoInternoEfectivo1 = new HashSet<MovimientoInternoEfectivo>();
            this.PagoLocalCajaEfectivo = new HashSet<PagoLocalCajaEfectivo>();
        }
    
        public int IdCajaEfectivo { get; set; }
        public string DetalleCajaEfectivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoInternoEfectivo> MovimientoInternoEfectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoInternoEfectivo> MovimientoInternoEfectivo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalCajaEfectivo> PagoLocalCajaEfectivo { get; set; }
    }
}
