//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequePropio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChequePropio()
        {
            this.CompraChequePropio = new HashSet<PagoLocalChequePropio>();
        }
    
        public int IdChequePropio { get; set; }
        public string NroCheque { get; set; }
        public string FechaEmision { get; set; }
        public string FechaPago { get; set; }
        public string Monto { get; set; }
        public string Destinatario { get; set; }
        public int IdEstadoCheque { get; set; }
        public int IdCuentaBanco { get; set; }
    
        public virtual CuentaBanco CuentaBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalChequePropio> CompraChequePropio { get; set; }
    }
}
