//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cheque()
        {
            this.PagoCheque = new HashSet<PagoCheque>();
            this.GastoCheque = new HashSet<GastoCheque>();
            this.CompraCheque = new HashSet<PagoLocalCheque>();
        }
    
        public int IdCheque { get; set; }
        public string Banco { get; set; }
        public string Titular { get; set; }
        public string NroCheque { get; set; }
        public string FechaEmision { get; set; }
        public string FechaPago { get; set; }
        public string Monto { get; set; }
        public int IdTipoCheque { get; set; }
        public int IdEstadoCheque { get; set; }
    
        public virtual TipoCheque TipoCheque { get; set; }
        public virtual EstadoCheque EstadoCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoCheque> PagoCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoCheque> GastoCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalCheque> CompraCheque { get; set; }
    }
}
