//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiudadFechasHorarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CiudadFechasHorarios()
        {
            this.RolAlumnoPracticas = new HashSet<RolAlumnoPracticas>();
        }
    
        public int IdCiudadFechasHorarios { get; set; }
        public int IdRolCiudadActiva { get; set; }
        public string Fecha { get; set; }
        public string IdRolCiudadActivaHorarios { get; set; }
    
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolAlumnoPracticas> RolAlumnoPracticas { get; set; }
    }
}
