//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System.Runtime.Serialization;

    public partial class CiudadPersonal
    {

        public int IdCiudadPersonal { get; set; }
        public int IdCiudad { get; set; }
        public string Periodo { get; set; }
        public int IdRolEmpleado { get; set; }
        [IgnoreDataMember]
        public virtual RolEmpleado RolEmpleado { get; set; }
        [IgnoreDataMember]
        public virtual Ciudad Ciudad { get; set; }
    }
}
