//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiudadFechasHorarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CiudadFechasHorarios()
        {
            this.RolAlumnoPracticas = new HashSet<RolAlumnoPracticas>();
        }
    
        public int IdCiudadFechasHorarios { get; set; }
        public int IdRolCiudadActiva { get; set; }
        public string Fecha { get; set; }
        public string IdRolCiudadActivaHorarios { get; set; }
    
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolAlumnoPracticas> RolAlumnoPracticas { get; set; }
    }
}
