//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiudadEquipos
    {
        public int IdCiudadEquipos { get; set; }
        public int IdAsignacionCiudadEquipo { get; set; }
        public int IdArmadoEquipo { get; set; }
    
        public virtual ArmadoEquipo ArmadoEquipo { get; set; }
        public virtual AsignacionCiudadEquipos AsignacionCiudadEquipos { get; set; }
    }
}
