//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancoTercero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaBancoTercero()
        {
            this.Transferencia = new HashSet<Transferencia>();
        }
    
        public int IdCuentaBanco { get; set; }
        public string Banco { get; set; }
        public string NroCuenta { get; set; }
        public string TipoCuenta { get; set; }
        public string CBU { get; set; }
        public string Titular { get; set; }
        public string Cuit { get; set; }
        public string Observaciones { get; set; }
        public bool CuentaActiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transferencia> Transferencia { get; set; }
    }
}
