//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deposito()
        {
            this.RendicionDeposito = new HashSet<RendicionDeposito>();
        }
    
        public int IdDeposito { get; set; }
        public int IdPersona { get; set; }
        public string Fecha { get; set; }
        public string Monto { get; set; }
        public int IdCuentaBanco { get; set; }
        public int IdEstadoDeposito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionDeposito> RendicionDeposito { get; set; }
        public virtual CuentaBanco CuentaBanco { get; set; }
        public virtual EstadoDeposito EstadoDeposito { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
