//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoAsignacionEquipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoAsignacionEquipo()
        {
            this.AsignacionCiudadEquipos = new HashSet<AsignacionCiudadEquipos>();
        }
    
        public int IdEstadoAsignacionEquipo { get; set; }
        public string DetalleEstadoASignacionEquipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionCiudadEquipos> AsignacionCiudadEquipos { get; set; }
    }
}
