//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoCheque
    {
        public int IdGastoCheque { get; set; }
        public int IdRendicionGasto { get; set; }
        public int IdCheque { get; set; }
    
        public virtual Cheque Cheque { get; set; }
        public virtual RendicionGasto RendicionGasto { get; set; }
    }
}
