//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoCheque
    {
        public int IdGastoCheque { get; set; }
        public int IdRendicionGasto { get; set; }
        public int IdCheque { get; set; }
    
        public virtual Cheque Cheque { get; set; }
        public virtual RendicionGasto RendicionGasto { get; set; }
    }
}
