//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaCiudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LineaCiudad()
        {
            this.CiudadPersonal = new HashSet<CiudadPersonal>();
        }
    
        public int IdLineaCiudad { get; set; }
        public int IdLinea { get; set; }
        public int IdCiudad { get; set; }
    
        public virtual Linea Linea { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiudadPersonal> CiudadPersonal { get; set; }
    }
}
