//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locacion()
        {
            this.CiudadActivaLocaciones = new HashSet<CiudadActivaLocaciones>();
            this.LocacionRolLocador = new HashSet<LocacionRolLocador>();
            this.RolLocacionAlojamiento = new HashSet<RolLocacionAlojamiento>();
            this.RolLocacionSalon = new HashSet<RolLocacionSalon>();
        }
    
        public int IdLocacion { get; set; }
        public string DetalleLocacion { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiudadActivaLocaciones> CiudadActivaLocaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocacionRolLocador> LocacionRolLocador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolLocacionAlojamiento> RolLocacionAlojamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolLocacionSalon> RolLocacionSalon { get; set; }
    }
}
