//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocacionRolLocador
    {
        public int IdLocacionRolLocador { get; set; }
        public int IdLocacion { get; set; }
        public int IdRolLocador { get; set; }
    
        public virtual RolLocador RolLocador { get; set; }
        public virtual Locacion Locacion { get; set; }
    }
}
