//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocacionRolLocador
    {
        public int IdLocacionRolLocador { get; set; }
        public int IdLocacion { get; set; }
        public int IdRolLocador { get; set; }
    
        public virtual RolLocador RolLocador { get; set; }
        public virtual Locacion Locacion { get; set; }
    }
}
