//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoInternoEfectivo
    {
        public int IdMovimientoInternoEfectivo { get; set; }
        public int IdCajaEfectivoOrigen { get; set; }
        public string FechaMovimientoInternoEfectivo { get; set; }
        public int IdcajaEfectivoDestino { get; set; }
        public string Monto { get; set; }
        public string Observaciones { get; set; }
    
        public virtual CajaEfectivo CajaEfectivo { get; set; }
        public virtual CajaEfectivo CajaEfectivo1 { get; set; }
    }
}
