//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.PagoTarjeta = new HashSet<PagoTarjeta>();
            this.RendicionPago = new HashSet<RendicionPago>();
            this.PagoCheque = new HashSet<PagoCheque>();
            this.RendicionVentaEquipo = new HashSet<RendicionVentaEquipo>();
        }
    
        public int IdPago { get; set; }
        public int IdPlanVendedorAlumno { get; set; }
        public string MontoPagado { get; set; }
        public int IdFormaPago { get; set; }
        public int IdItemPagado { get; set; }
        public string NroRecibo { get; set; }
    
        public virtual FormaPago FormaPago { get; set; }
        public virtual PlanVendedorAlumno PlanVendedorAlumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoTarjeta> PagoTarjeta { get; set; }
        public virtual ItemPagado ItemPagado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionPago> RendicionPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoCheque> PagoCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionVentaEquipo> RendicionVentaEquipo { get; set; }
    }
}
