//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoLocal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PagoLocal()
        {
            this.CompraTransferencia = new HashSet<PagoLocalTransferencia>();
            this.PagoLocalChequePropio = new HashSet<PagoLocalChequePropio>();
            this.PagoLocalTarjeta = new HashSet<PagoLocalTarjeta>();
            this.PagoLocalCheque = new HashSet<PagoLocalCheque>();
            this.GastoLocal = new HashSet<GastoLocal>();
            this.Compra = new HashSet<Compra>();
            this.PagoLocalCajaEfectivo = new HashSet<PagoLocalCajaEfectivo>();
            this.PagoLocalEnvio = new HashSet<PagoLocalEnvio>();
        }
    
        public int IdPagoLocal { get; set; }
        public string FechaPago { get; set; }
        public int IdFormaPagoLocal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalTransferencia> CompraTransferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalChequePropio> PagoLocalChequePropio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalTarjeta> PagoLocalTarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalCheque> PagoLocalCheque { get; set; }
        public virtual FormaPagoLocal FormaPagoLocal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoLocal> GastoLocal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalCajaEfectivo> PagoLocalCajaEfectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoLocalEnvio> PagoLocalEnvio { get; set; }
    }
}
