//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoLocalTarjeta
    {
        public int IdPagoLocalTarjeta { get; set; }
        public int IdPagoLocal { get; set; }
        public int IdTarjetaPropia { get; set; }
        public string CantCuotas { get; set; }
        public string Monto { get; set; }
    
        public virtual TarjetaPropia TarjetaPropia { get; set; }
        public virtual PagoLocal PagoLocal { get; set; }
    }
}
