//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoTarjeta
    {
        public int IdPagoTarjeta { get; set; }
        public int IdPago { get; set; }
        public string MontoAPagar { get; set; }
        public int IdCuotas { get; set; }
        public string Recargo { get; set; }
        public string MontoTotal { get; set; }
        public string NumeroTarjeta { get; set; }
        public string EmisorTarjeta { get; set; }
        public string CodSeguridad { get; set; }
        public string Vencimiento { get; set; }
        public string TitularTarjeta { get; set; }
        public string DNI { get; set; }
        public string CodAut { get; set; }
        public int IdEstadoPagoTarjeta { get; set; }
    
        public virtual Pago Pago { get; set; }
        public virtual EstadoPagoTarjeta EstadoPagoTarjeta { get; set; }
        public virtual CoeficTarjetas CoeficTarjetas { get; set; }
    }
}
