//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisoAcceso
    {
        public int IdPermisoAcceso { get; set; }
        public int IdPermiso { get; set; }
        public string DetalleAcceso { get; set; }
        public bool PermisoActivo { get; set; }
    
        public virtual Permiso Permiso { get; set; }
    }
}
