//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanVendedorAlumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanVendedorAlumno()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int IdPlanVendedorAlumno { get; set; }
        public string NroRecibo { get; set; }
        public int IdRolCiudadActivaPlan { get; set; }
        public int IdRolAlumno { get; set; }
        public int IdRolVendedor { get; set; }
        public string ObservacionGerente { get; set; }
        public string ObservacionOficinaBaires { get; set; }
    
        public virtual RolAlumno RolAlumno { get; set; }
        public virtual RolVendedor RolVendedor { get; set; }
        public virtual RolCiudadActivaPlan RolCiudadActivaPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
