//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendicionPersonaCiudad
    {
        public int IdRendicionPersonaCiudad { get; set; }
        public int IdPersona { get; set; }
        public int IdRolCiudadActiva { get; set; }
        public int IdEstadoRendicion { get; set; }
    
        public virtual EstadoRendicion EstadoRendicion { get; set; }
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
