//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendicionPersonaCiudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RendicionPersonaCiudad()
        {
            this.RendicionPago = new HashSet<RendicionPago>();
            this.RendicionGasto = new HashSet<RendicionGasto>();
            this.RendicionDeposito = new HashSet<RendicionDeposito>();
        }
    
        public int IdRendicionEmpleadoCiudad { get; set; }
        public int IdRolEmpleado { get; set; }
        public int IdRolCiudadActiva { get; set; }
        public int IdEstadoRendicion { get; set; }
    
        public virtual EstadoRendicion EstadoRendicion { get; set; }
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionPago> RendicionPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionGasto> RendicionGasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionDeposito> RendicionDeposito { get; set; }
        public virtual RolEmpleado RolEmpleado { get; set; }
    }
}
