//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendicionGasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RendicionGasto()
        {
            this.GastoCheque = new HashSet<GastoCheque>();
        }
    
        public int IdRendicionGasto { get; set; }
        public int IdRendicionEmpleadoCiudad { get; set; }
        public int IdGastoBase { get; set; }
        public string Monto { get; set; }
        public int IdFormaPago { get; set; }
        public string Observaciones { get; set; }
    
        public virtual RendicionPersonaCiudad RendicionPersonaCiudad { get; set; }
        public virtual GastoBase GastoBase { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoCheque> GastoCheque { get; set; }
    }
}
