//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendicionDeposito
    {
        public int IdRendicionDeposito { get; set; }
        public int IdRendicionEmpleadoCiudad { get; set; }
        public int IdDeposito { get; set; }
    
        public virtual RendicionPersonaCiudad RendicionPersonaCiudad { get; set; }
        public virtual Deposito Deposito { get; set; }
    }
}
