//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendicionPersonaCiudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RendicionPersonaCiudad()
        {
            this.RendicionPago = new HashSet<RendicionPago>();
            this.RendicionGasto = new HashSet<RendicionGasto>();
            this.RendicionDeposito = new HashSet<RendicionDeposito>();
            this.RendicionVale = new HashSet<RendicionVale>();
            this.RendicionSueldo = new HashSet<RendicionSueldo>();
        }
    
        public int IdRendicionEmpleadoCiudad { get; set; }
        public int IdRolEmpleado { get; set; }
        public int IdRolCiudadActiva { get; set; }
        public int IdEstadoRendicion { get; set; }
    
        public virtual EstadoRendicion EstadoRendicion { get; set; }
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionPago> RendicionPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionGasto> RendicionGasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionDeposito> RendicionDeposito { get; set; }
        public virtual RolEmpleado RolEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionVale> RendicionVale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionSueldo> RendicionSueldo { get; set; }
    }
}
