//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolAlumnoPracticas
    {
        public int IdRolAlumnoPracticas { get; set; }
        public int IdCiudadFechasHorarios { get; set; }
        public string TipoPractica { get; set; }
        public string EstadoPractica { get; set; }
        public int IdRolAlumno { get; set; }
    
        public virtual RolAlumno RolAlumno { get; set; }
        public virtual CiudadFechasHorarios CiudadFechasHorarios { get; set; }
    }
}
