//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolAlumno
    {
        public int IdRolAlumno { get; set; }
        public int IdPersona { get; set; }
        public int IdCapacitacion { get; set; }
        public int IdInformeCiudadHorarios { get; set; }
        public int IdEstadoAlumno { get; set; }
    
        public virtual EstadoAlumno EstadoAlumno { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
