//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolAlumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolAlumno()
        {
            this.PlanVendedorAlumno = new HashSet<PlanVendedorAlumno>();
            this.AlumnoHorario = new HashSet<AlumnoHorario>();
            this.RolAlumnoPresentismo = new HashSet<RolAlumnoPresentismo>();
            this.RolAlumnoPracticas = new HashSet<RolAlumnoPracticas>();
        }
    
        public int IdRolAlumno { get; set; }
        public int IdPersona { get; set; }
        public int IdCapacitacion { get; set; }
        public int IdEstadoAlumno { get; set; }
    
        public virtual EstadoAlumno EstadoAlumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanVendedorAlumno> PlanVendedorAlumno { get; set; }
        public virtual Capacitacion Capacitacion { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoHorario> AlumnoHorario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolAlumnoPresentismo> RolAlumnoPresentismo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolAlumnoPracticas> RolAlumnoPracticas { get; set; }
    }
}
