//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolAlumnoPresentismo
    {
        public int IdRolAlumnoPresentismo { get; set; }
        public int IdRolAlumno { get; set; }
        public string NumeroClase { get; set; }
        public string EstadoClase { get; set; }
    
        public virtual RolAlumno RolAlumno { get; set; }
    }
}
