//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolAlumnoPracticas
    {
        public int IdRolAlumnoPracticas { get; set; }
        public int IdCiudadFechasHorarios { get; set; }
        public string TipoPractica { get; set; }
        public string EstadoPractica { get; set; }
        public int IdRolAlumno { get; set; }
    
        public virtual RolAlumno RolAlumno { get; set; }
        public virtual CiudadFechasHorarios CiudadFechasHorarios { get; set; }
    }
}
