//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolCiudadActivaGastos
    {
        public int IdRolCiudadActivaGastos { get; set; }
        public int IdRolCiudadActiva { get; set; }
        public int IdGastoBase { get; set; }
        public string ValorEstimMensual { get; set; }
        public string Observaciones { get; set; }
    
        public virtual GastoBase GastoBase { get; set; }
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
    }
}
