//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolCiudadEnProceso
    {
        public int IdRolCiudadEnProceso { get; set; }
        public int IdCiudad { get; set; }
        public string InformeCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
