//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolCiudadActivaHorario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolCiudadActivaHorario()
        {
            this.RolAlumno = new HashSet<RolAlumno>();
        }
    
        public int IdRolCiudadActivaHorario { get; set; }
        public int IdDia { get; set; }
        public int IdHorario { get; set; }
        public int IdRolCiudadActiva { get; set; }
    
        public virtual Horario Horario { get; set; }
        public virtual Dia Dia { get; set; }
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolAlumno> RolAlumno { get; set; }
    }
}
