//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolCiudadActiva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolCiudadActiva()
        {
            this.CiudadActivaLocaciones = new HashSet<CiudadActivaLocaciones>();
            this.RolCiudadActivaPlan = new HashSet<RolCiudadActivaPlan>();
            this.RolCiudadActivaHorario = new HashSet<RolCiudadActivaHorario>();
            this.RendicionCobradorCiudad = new HashSet<RendicionPersonaCiudad>();
            this.RolCiudadActivaGastos = new HashSet<RolCiudadActivaGastos>();
            this.AsignacionCiudadEquipos = new HashSet<AsignacionCiudadEquipos>();
        }
    
        public int IdRolCiudadActiva { get; set; }
        public int IdCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiudadActivaLocaciones> CiudadActivaLocaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolCiudadActivaPlan> RolCiudadActivaPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolCiudadActivaHorario> RolCiudadActivaHorario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionPersonaCiudad> RendicionCobradorCiudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolCiudadActivaGastos> RolCiudadActivaGastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionCiudadEquipos> AsignacionCiudadEquipos { get; set; }
    }
}
