//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolCiudadActivaHorario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolCiudadActivaHorario()
        {
            this.AlumnoHorario = new HashSet<AlumnoHorario>();
        }
    
        public int IdRolCiudadActivaHorario { get; set; }
        public int IdDia { get; set; }
        public int IdHorario { get; set; }
        public int IdRolCiudadActiva { get; set; }
    
        public virtual Horario Horario { get; set; }
        public virtual Dia Dia { get; set; }
        public virtual RolCiudadActiva RolCiudadActiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoHorario> AlumnoHorario { get; set; }
    }
}
