//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolLocacionSalon
    {
        public int IdRolLocacionSalon { get; set; }
        public int IdLocacion { get; set; }
        public string Tamaño { get; set; }
        public string Mesas { get; set; }
        public string Sillas { get; set; }
        public string AireAcondicionado { get; set; }
        public string Calefaccion { get; set; }
    
        public virtual Locacion Locacion { get; set; }
    }
}
