//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolLocador
    {
        public int IdRolLocador { get; set; }
        public int IdPersona { get; set; }
        public string Condicion { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
