//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolLocacionSalon
    {
        public int IdRolLocacionSalon { get; set; }
        public int IdLocacion { get; set; }
        public string Tamaño { get; set; }
        public string Mesas { get; set; }
        public string Sillas { get; set; }
        public string AireAcondicionado { get; set; }
        public string Calefaccion { get; set; }
    
        public virtual Locacion Locacion { get; set; }
    }
}
