//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolVendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolVendedor()
        {
            this.PlanVendedorAlumno = new HashSet<PlanVendedorAlumno>();
        }
    
        public int IdRolVendedor { get; set; }
        public int IdRolEmpleado { get; set; }
        public int IdSubgerente { get; set; }
        public int IdGerente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanVendedorAlumno> PlanVendedorAlumno { get; set; }
        public virtual RolEmpleado RolEmpleado { get; set; }
        public virtual RolEmpleado RolEmpleado1 { get; set; }
        public virtual RolEmpleado RolEmpleado2 { get; set; }
    }
}
