//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolVendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolVendedor()
        {
            this.PlanVendedorAlumno = new HashSet<PlanVendedorAlumno>();
        }
    
        public int IdRolVendedor { get; set; }
        public int IdRolEmpleado { get; set; }
        public int IdSubgerente { get; set; }
        public int IdGerente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanVendedorAlumno> PlanVendedorAlumno { get; set; }
        public virtual RolEmpleado RolEmpleado { get; set; }
    }
}
