//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValeFinanciacion
    {
        public int IdValeFinanciacion { get; set; }
        public int IdVale { get; set; }
        public string Monto { get; set; }
        public string PeriodoDescuento { get; set; }
    
        public virtual Vale Vale { get; set; }
    }
}
