//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vale()
        {
            this.RendicionVale = new HashSet<RendicionVale>();
            this.ValeFinanciacion = new HashSet<ValeFinanciacion>();
        }
    
        public int IdVale { get; set; }
        public string Fecha { get; set; }
        public int IdRolEmpleado { get; set; }
        public string Monto { get; set; }
        public string Observaciones { get; set; }
    
        public virtual RolEmpleado RolEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendicionVale> RendicionVale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValeFinanciacion> ValeFinanciacion { get; set; }
    }
}
