//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCManager.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValeFinanciacion
    {
        public int IdValeFinanciacion { get; set; }
        public int IdVale { get; set; }
        public string Monto { get; set; }
        public string PeriodoDescuento { get; set; }
    
        public virtual Vale Vale { get; set; }
    }
}
