//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int IdPersona { get; set; }
        public string Apellido { get; set; }
        public string Nombres { get; set; }
        public System.DateTime FechaNac { get; set; }
        public string DNI { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public string Ciudad { get; set; }
        public string Provincia { get; set; }
        public string Celular { get; set; }
        public string TelAlternativo { get; set; }
        public string EstadoCivil { get; set; }
        public string Mail { get; set; }
    }
}
